# Generated by Django 4.0.3 on 2022-04-01 08:45

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import imagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', imagefield.fields.ImageField(blank=True, height_field='img_height', upload_to='contact/', width_field='img_width')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=20)),
                ('per_address', models.CharField(max_length=250)),
                ('pr_country', django_countries.fields.CountryField(max_length=2)),
                ('cor_address', models.CharField(max_length=250)),
                ('cr_country', django_countries.fields.CountryField(max_length=2)),
                ('tax_id', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('Age', models.IntegerField(max_length=100)),
                ('high_education', models.CharField(max_length=250)),
                ('occupation', models.CharField(max_length=150)),
                ('no_of_experience', models.IntegerField(max_length=100)),
                ('parent_f_name', models.CharField(max_length=50)),
                ('parent_l_name', models.CharField(max_length=50)),
                ('pas_no', models.CharField(max_length=16)),
                ('pas_country', django_countries.fields.CountryField(max_length=2)),
                ('telephone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_individual', models.CharField(choices=[('company', 'company'), ('indivisual', 'indivisual')], max_length=20)),
                ('company', models.CharField(blank=True, max_length=250)),
                ('job_position', models.CharField(blank=True, max_length=250)),
                ('img_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('img_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('img_ppoi', imagefield.fields.PPOIField(default='0.5x0.5', max_length=20)),
            ],
        ),
    ]
