# Generated by Django 4.0.3 on 2022-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_is_individual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_individual',
        ),
        migrations.AddField(
            model_name='contact',
            name='indivisual',
            field=models.BooleanField(default=True),
        ),
    ]
