# Generated by Django 4.0.3 on 2022-04-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_company_alter_contact_indivisual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='company_n',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='indivisual',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='job_position',
        ),
    ]
