# Generated by Django 4.0.3 on 2022-04-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='no_of_experience',
            field=models.IntegerField(),
        ),
    ]
