# Generated by Django 3.1.5 on 2021-09-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutorydeduction',
            name='local_service_tax',
            field=models.FloatField(default=0.0),
        ),
    ]
