# Generated by Django 4.0.3 on 2022-03-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_admin', '0002_audittrail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
