# Generated by Django 3.1.12 on 2022-04-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20220418_0047'),
        ('crm_app', '0003_alter_bankdetails_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_more_detail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CustomerSupervision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date_of_birth', models.DateField()),
                ('age', models.CharField(max_length=20)),
                ('passport_no', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('sub_county', models.CharField(max_length=20)),
                ('parish', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_bank', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('bank_account', models.CharField(max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm_app.customer')),
            ],
        ),
    ]
