# Generated by Django 3.1.12 on 2022-04-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_auto_20220418_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='passport_no',
        ),
    ]
