# Generated by Django 4.0.3 on 2022-04-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_alter_add_more_detail_id_alter_allowance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='parish',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
