# Generated by Django 4.0.3 on 2022-04-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_alter_add_more_detail_id_alter_allowance_id_and_more'),
        ('invoice1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='b_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.customer'),
        ),
    ]
