# Generated by Django 3.1.12 on 2022-04-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_auth', '0002_alter_solitonuser_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solitonuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
