# Generated by Django 3.1.12 on 2022-05-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_auth', '0004_auto_20220503_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
