# Generated by Django 4.0.3 on 2022-03-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationdetail',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation_details.department'),
        ),
        migrations.AlterField(
            model_name='organisationdetail',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation_details.position'),
        ),
        migrations.AlterField(
            model_name='organisationdetail',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation_details.team'),
        ),
    ]
